---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-module
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-module
  name: demo-module-web-service
  annotations:
    metallb.universe.tf/address-pool: demo-module
spec:
  selector:
    app: demo-module-web
  ports:
  - name: web-8080
    port: 8080
    targetPort: 8080
  - name: web-8787
    port: 8787
    targetPort: 8787
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: demo-module
  labels:
    app: demo-module-web
    owner: extracredit
    type: web-app
    project: demo-module
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: demo-module-web
  template:
    metadata:
      labels:
        app: demo-module-web
    spec:
      containers:
      - name: demo-module
        image: registry.pgx.local/demo-module/demo-module:0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
          - name: DEBUG_CONFIG
            valueFrom:
              configMapKeyRef:
                name: demo-module-web-config
                key: DEBUG_CONFIG
          - name: WELCOME_MESSAGE
            valueFrom:
              configMapKeyRef:
                name: demo-module-web-config
                key: WELCOME_MESSAGE

  
